// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3mazEdTdOg-WRAXWHv5g5rz6c1ulzTbc',
    appId: '1:183948499719:android:25bf68c2ee46ff5f8783a2',
    messagingSenderId: '183948499719',
    projectId: 'sample-88b5b',
    databaseURL: 'https://sample-88b5b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sample-88b5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDohVroIxq4Uy4gsM9b0pgQ-DW2h5LLl9E',
    appId: '1:183948499719:ios:0c09caf7291a80db8783a2',
    messagingSenderId: '183948499719',
    projectId: 'sample-88b5b',
    databaseURL: 'https://sample-88b5b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sample-88b5b.firebasestorage.app',
    iosBundleId: 'com.example.emcus',
  );
}
